name: Build & Release EXE

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'      # v1.0.0 gibi bir tag push’ladığında tetiklesin

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout kodu
      uses: actions/checkout@v3

    - name: Python’ı kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Gereksinimleri yükle
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: EXE’yi derle
      run: |
        pyinstaller --onefile --windowed hesap.py
      # Eğer farklı girdilerin (config, ikon vs.) kopyalanması gerekirse ekle:
      #   cp assets/*.ico dist/

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload EXE to Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/hesap.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
