name: Build & Release EXE

on:
  workflow_dispatch: {}
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v3

      - name: Python’ı kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gereksinimleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy pandas matplotlib pillow XlsxWriter pywin32

      - name: EXE’yi derle
        run: |
          pyinstaller --onefile --windowed --icon=app.ico  --collect-all numpy --collect-all pandas --collect-all pywin32 --collect-all matplotlib hesap.py

      - id: create_release
        if: github.event_name == 'push'
        name: Release oluştur
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: EXE’yi Release’e ekle
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/hesap.exe
          asset_name: hesap.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
