on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.x'
      - run: pip install pyinstaller numpy pandas matplotlib pillow XlsxWriter pywin32

      - name: EXE’yi derle
        run: python -m PyInstaller --onefile --windowed --icon=app.ico hesap.py

      - id: create_release
        uses: actions/create-release@v1
        with:
          tag_name:      ${{ github.ref_name }}
          release_name:  Release ${{ github.ref_name }}
          draft:         false
          prerelease:    false
          allow_updates: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release asset yükle
        uses: actions/upload-release-asset@v1
        with:
          upload_url:        ${{ steps.create_release.outputs.upload_url }}
          asset_path:        dist/hesap.exe
          asset_name:        hesap.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
