name: Build & Release EXE

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v3

      - name: Python’ı kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Gereksinimleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller numpy pandas matplotlib pillow XlsxWriter pywin32

      - name: EXE’yi derle
        run: |
          python -m PyInstaller --onefile --windowed --icon=app.ico hesap.py

      - name: Release oluştur ve EXE’yi yükle
        uses: softprops/action-gh-release@v1
        with:
          tag_name:     ${{ github.ref_name }}
          files:        dist/hesap.exe
          draft:        false
          prerelease:   false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
